# Generated by Django 4.2.4 on 2023-09-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_car_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SiteUser',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
