# Generated by Django 4.2.4 on 2023-09-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_siteuser_options_alter_siteuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='updated_at',
        ),
    ]
