# Generated by Django 4.2.4 on 2023-09-15 21:51

import base.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_siteuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
                ('objects', base.base.CustomUserManager()),
            ],
        ),
    ]
